### ISSUE TITLE
Allow title and order to be selected

### ISSUE THREAD

**Issue by melohagan** [R2bEEaton/bb-kanban-draggable#1]
Hey @R2bEEaton 

Just started checking out your plugin. First thing I noticed is that it would be nice if the Title and Order fields could be selected from dropdowns, rather than having to make sure your table has those columns.

For example, this is done in the Options Picker component when you select data provider as the source:

https://docs.budibase.com/docs/option-picker#using-a-data-provider

```json
{
        "type": "field",
        "label": "Label column",
        "key": "labelColumn",
        "dependsOn": {
          "setting": "optionsSource",
          "value": "provider"
        }
      },
      {
        "type": "field",
        "label": "Value column",
        "key": "valueColumn",
        "dependsOn": {
          "setting": "optionsSource",
          "value": "provider"
        }
      },
```

**Comment by R2bEEaton** [comment]
This is a great suggestion! I'll work on this and get back to you.

**Comment by R2bEEaton** [comment]
@melohagan Ok the latest release should be good now. I also added some QoL changes like the ability to change sort order and whether to show the order value in the list.
